version: "3"
services:
  db:
    container_name: db
    image: mysql:8
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_DATABASE: "app_django"
      MYSQL_ALLOW_EMPTY_PASSWORD : "true"
  app:
    build: .
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    depends_on:
      - db
