version: "3"
services:
  db:
    container_name: db
    image: mysql:8
    hostname: db
    environment:
      MYSQL_DATABASE: "app_django"
      MYSQL_ALLOW_EMPTY_PASSWORD : "true"
    ports:
      - "3306:3306"

  app:
    build: .
    restart: on-failure
    command: sh -c "./wait-for db:3306 -t 0 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      - .:/django
    ports:
      - "8000:8000"
    depends_on:
      - db
